//User
export const SET_USER_LOGGED_IN = "SET_USER_LOGGED_IN";
export const SET_ADMIN_LOGGED_IN = "SET_ADMIN_LOGGED_IN";
export const ADD_LOGGED_IN_BY = "ADD_LOGGED_IN_BY";
export const REMOVE_LOGGED_IN_BY = "REMOVE_LOGGED_IN_BY";
export const ADMINNAME_FOR_ASIDEBAR_DATA_INTO_REDUX_STORE =
  "ADMINNAME_FOR_ASIDEBAR_DATA_INTO_REDUX_STORE";
